//
// Generated by CDQI on 2018-12-09.
//
// This file was generated by a tool. Further invocations of this tool will overwrite this file.
// Edit it at your own risk.
//

import CoreDataQueryInterface

public final class PassengerAttribute: EntityAttribute, Subqueryable {
    public private(set) lazy var age: Integer32Attribute = { Integer32Attribute(key: "age", parent: self) }()
    public private(set) lazy var name: StringAttribute = { StringAttribute(key: "name", parent: self) }()
    public private(set) lazy var reservations: ReservationAttribute = { ReservationAttribute(key: "reservations", parent: self) }()
}

extension Passenger: Entity {
    public typealias CDQIAttribute = PassengerAttribute
}

