//
// Generated by CDQI on 2018-12-11.
//
// This file was generated by a tool. Further invocations of this tool will overwrite this file.
// Edit it at your own risk.
//

import CoreDataQueryInterface

public final class TrainAttribute: EntityAttribute, Subqueryable {
    public private(set) lazy var companyName: StringAttribute = { StringAttribute(key: "companyName", parent: self) }()
    public private(set) lazy var trainNumber: Integer32Attribute = { Integer32Attribute(key: "trainNumber", parent: self) }()
    public private(set) lazy var reservations: ReservationAttribute = { ReservationAttribute(key: "reservations", parent: self) }()
}

extension Train: Entity {
    public typealias CDQIAttribute = TrainAttribute
}

